# --- Basic options --- #
title: SpellBot
description: The Discord bot for SpellTable
author: "@lexicalunit"

# --- List of links in the navigation bar --- #
navbar-links:
  SpellTable: "https://spelltable.com"
  Support Me: "https://ko-fi.com/Y8Y51VTHZ"
  Development: "https://github.com/lexicalunit/spellbot"
  "#BLM": "https://blacklivesmatters.carrd.co/"

# --- Logo --- #
avatar: "/assets/img/avatar-icon.png"
round-avatar: false
# image logo in the top-left corner instead of the title text
#title-img: /path/to/image

# --- Footer options --- #
social-network-links:
  email: "amy@lexicalunit.com"
  github: lexicalunit
  twitter: lexicalunit
  rss: true

# --- General options --- #
share-links-active:
  twitter: true
  facebook: false
  linkedin: false
  vk: false

url-pretty: "SpellBot.io"
link-tags: false
excerpt_length: 50

# --- Colours / background image --- #
navbar-col: "#0d1117"
navbar-text-col: "#718096"
navbar-border-col: "#1a202c"
page-col: "#1a202c"
page-text-col: "#FFFFFF"
link-col: "#ffb342"
hover-col: "#ffd160"
footer-col: "#0d1117"
footer-text-col: "#718096"
footer-link-col: "#765bff"
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# --- Web Statistics Section --- #
gtag: "UA-174106299-1" # Google Analytics gtag.js ID to track using gtag
# google_analytics: "UA-174106299-1" # Google Analytics ID to track using GA
# gtm: "" # Google Tag Manager ID
# matomo:
#   site_id: "9"
#   uri: "demo.wiki.pro"
#   opt-out: true

# --- Comments --- #
# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, first invite `staticmanlab` as a collaborator to your repository and
# accept the invitation by going to `https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>`.
# Then uncomment the following section and fill in "repository" and "branch".
# If you want to use reCaptcha for staticman (optional for spam protection), then fill
# in the "siteKey" and "secret" parameters below and also in `staticman.yml`.
# See more details at https://staticman.net/
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # (optional) URL of your own deployment, with a trailing slash eg. https://<your-api>/v3/entry/github/ (will fallback to a public GitLab instance)
#  reCaptcha:
#    siteKey  : # Use your own site key, you need to apply for one on Google
#    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #
title-separator: "-"
date_format: "%B %-d, %Y"

# --- GitHub Pages Settings --- #
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
      readtime: false
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
