name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - CHANGELOG.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - CHANGELOG.md

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9"]
        database-url: ["postgresql://postgres:postgres@localhost:5432/postgres"]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        git --version
        python --version
        python -m pip install --upgrade pip
        pip --version
        pip install poetry
        poetry --version
        poetry install
        pip install -U "aiohttp==3.8.1" "pytest-aiohttp==1.0.4"

    - name: Run Tests
      run: |
        poetry run pytest -vv --cov --cov-report=html --cov-report=xml
      env:
        DATABASE_URL: ${{ matrix.database-url }}

    - name: Send Reports to Codecov
      uses: codecov/codecov-action@v1
      env:
        PYTHON: ${{ matrix.python-version }}
        DB_URL: ${{ matrix.database-url }}
      with:
        env_vars: PYTHON,DB_URL
